package com.kiva.kivadiscordbridge;

import com.fox2code.foxloader.loader.ServerMod;
import com.fox2code.foxloader.network.NetworkPlayer;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.nio.file.FileAlreadyExistsException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;

public class KivaDiscordBridgeServer extends KivaDiscordBridge implements ServerMod {
    public static DiscordAPI discordAPI = new DiscordAPI();
    public static String loggingPrefix = "[KivaDiscordBridge] ";
    public static final String kivaDiscordBridgeBasePath = "mods/KivaDiscordBridge/";
    public static String configFilename = kivaDiscordBridgeBasePath + "config.txt";

    private static Config config = new Config();

    @Override
    public void onInit() {
        config.loadFromFile(configFilename);
        System.out.println("KivaDiscordBridge initialized");
    }

    @Override
    public void onServerStop(NetworkPlayer.ConnectionType connectionType) {
        // Make sure mods/KivaDiscordBridge directory exists
        Path modsPath = Paths.get(kivaDiscordBridgeBasePath);
        try {
            Files.createDirectory(modsPath);
        } catch (IOException e) {
            if (!(e instanceof FileAlreadyExistsException)) {
                ServerMod.getGameInstance().logWarning(loggingPrefix + "Failed to create directory: " + kivaDiscordBridgeBasePath);
                e.printStackTrace();
                return;
            }
        }

        File f = new File(configFilename);
        if (f.exists())
            return;

        try {
            FileWriter fileWriter = new FileWriter(configFilename);
            fileWriter.write("# Default empty config file generated by KivaDiscordBridge\n");
            fileWriter.write("bot-token=\n");
            fileWriter.write("channel-id=\n");
            fileWriter.close();
        } catch (IOException e) {
            ServerMod.getGameInstance().logWarning(loggingPrefix + "Failed to write empty default config to " + configFilename);
        }
    }
}
